### ISSUE TITLE
parser fails trying to get precinct number

### ISSUE THREAD

**Issue by mscarey** [open-austin/eviction-hearing-parser#38]
When following the readme and using the command `python parse_hearings.py test_input.csv result.json`, I've had the CLI fail several times trying to get the precinct number from the search result page. I don't completely understand the error yet. This doesn't happen when running the tests on the example files, so it may have been caused by some design change in the county website. We probably need two changes: 

1. parse the precinct number from the search result page successfully

2. rewrite the function so it logs an error and continues running when it fails to scrape this feature, instead of failing and exiting

**Comment by normaljosh** [comment]
I've been seeing this issue sporadically on the same caseids which sometimes pull correctly, so I don't think it's a website change. Trying to catch it in action, but I suspect it's due to the page not fully loading (precinct number is the first item taken from the soup object in get_parsed_case). 

Might be best to code in something to log and retry the same caseid once or twice upon a fail to see if it reloads correctly.
